### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by mishrabiswajit** [Project-Awaken/official_devices#1]
## Device you want to apply for
```
Realme 5 Series (RMX1911, RMX2030, RMX1925 ,RMX1927) (unified codename "r5x")
```

## Device tree sources

```
https://github.com/mishrabiswajit/device_realme_r5x
https://github.com/mishrabiswajit/kernel_realme_r5x
https://github.com/mishrabiswajit/vendor_realme_r5x
```

## Link to the platform where you have released your unofficial build
```
https://t.me/rmx_1911
```

## Other ROM's you maintain officially or unofficially
```
PIXEL OS , PROJECT STREAK
```

## Bugs on unofficial build
```
offline charging
```

## How long have you been building for?
```
3 Months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@yourdeathiswaitingforyou
```

**Comment by PainKiller3** [comment]
https://github.com/mishrabiswajit/device_realme_r5x/commit/f3b1b08bf131ec1787ca97d5c4312ca2649c6d93


https://github.com/mishrabiswajit/device_realme_r5x/commit/1ee3a486773c2a1ccc13640af20ebe9649690577

???

**Comment by mishrabiswajit** [comment]
> [mishrabiswajit/device_realme_r5x@f3b1b08](https://github.com/mishrabiswajit/device_realme_r5x/commit/f3b1b08bf131ec1787ca97d5c4312ca2649c6d93)
> 
> [mishrabiswajit/device_realme_r5x@1ee3a48](https://github.com/mishrabiswajit/device_realme_r5x/commit/1ee3a486773c2a1ccc13640af20ebe9649690577)
> 
> ???

see now

**Comment by KrishnakantShedge** [comment]
Clean these two commits:
https://github.com/mishrabiswajit/device_realme_r5x/commit/c5e3543ba04c5c09206b9adfc9dbb646efece8de

https://github.com/mishrabiswajit/device_realme_r5x/commit/6422bba0e4bdecfbcfea57f1480740de7d8e2b5b

And why do you need this?
https://github.com/mishrabiswajit/device_realme_r5x/commit/6b696f7960fda66289091e3ecc7ca9f0ec4cb98f

**Comment by mishrabiswajit** [comment]
> And why do you need this? [mishrabiswajit/device_realme_r5x@6b696f7](https://github.com/mishrabiswajit/device_realme_r5x/commit/6b696f7960fda66289091e3ecc7ca9f0ec4cb98f)

RMX2050 is a similar device (narzo 20A) but has A11
so updated from it rather than our stock

**Comment by KrishnakantShedge** [comment]
> 

Why not just use from source?

**Comment by mishrabiswajit** [comment]
> Why not just use from source?

because source one gives problem in via and airtel sims (in volte)

**Comment by KrishnakantShedge** [comment]
Accepted
