### ISSUE TITLE
New maintainer for Haydn

### ISSUE THREAD

**Issue by 1xtAsh** [Project-Awaken/official_devices#113]
## Device you want to apply for
Device name: Mi 11x Pro/ Redmi k40 pro
Codename: Haydn

## Device tree sources

```
 Device : https://github.com/1xtAsh/android_device_xiaomi_haydn
 Device Common : https://github.com/1xtAsh/android_device_xiaomi_sm8350-common 
 Vendor : https://github.com/1xtAsh/proprietary_vendor_xiaomi_haydn 
 Vendor Common : https://github.com/1xtAsh/proprietary_vendor_xiaomi_sm8350-common 
 Kernel  : https://github.com/1xtAsh/android_kernel_xiaomi_sm8350
```

## Link to the platform where you have released your unofficial build
```
https://t.me/mi11xproChannel
https://sourceforge.net/projects/the-haydn-project/files/awaken-4.3-ursa-haydn-unofficial-1144-20240221.zip/download
```

## Other ROM's you maintain officially or unofficially
```
SuperiorOS-Official
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
more than a year
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
https://t.me/AshraySingh
```

**Comment by KrishnakantShedge** [comment]
You already are maintaining more than 3 ROMS (AwakenOS, SuperiorOS, LineageOS, Project Blaze, GenesisOS) which is against the Maintainer requirements.
