### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by User132New** [Project-Awaken/official_devices#114]
## Device you want to apply for
```
Redmi Note 10S/11SE India/Poco M5s(rosemary/secret/maltose/rosemary_p)
```

## Device tree sources

```
https://github.com/User132New/android_device_xiaomi_rosemary/tree/ursa_4.3
https://github.com/xiaomi-mt6785-dev/android_kernel_xiaomi_mt6785
https://github.com/User132New/android_vendor_xiaomi_rosemary
```

## Link to the platform where you have released your unofficial build
```
https://github.com/User132New/android_device_xiaomi_rosemary/releases/tag/ursa_4.3-1
https://github.com/User132New/android_device_xiaomi_rosemary/releases/tag/ursa_4.3-0
```

## Other ROM's you maintain officially or unofficially
```
Halcyon Official
```

## Bugs on unofficial build
```
Battery Widget not respoding.
```

## How long have you been building for?
```
Six Months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
https://t.me/bera_nhi
@bera_nhi
```

**Comment by User132New** [comment]
Fast charging is not working

**Comment by User132New** [comment]
Will be busy for next month, so closing for now

**Comment by KrishnakantShedge** [comment]
Rejected because:
1. You have fast charging and deep sleep bugs which should be fixed before applying.
2. Not enough contributions from you.
3. No proper commit messages.
