### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Thereache** [Project-Awaken/official_devices#117]
## Device you want to apply for
```
Poco X5 Pro 5g/redmi Note 12 5g SE(redwood/redwoodin)
```

## Device tree sources

```
https://github.com/Redwood-trees/device_xiaomi_redwood.git
https://github.com/Redwood-trees/kernel_xiaomi_redwood-atomx
https://github.com/Redwood-trees/vendor_xiaomi_redwood.git
```

## Link to the platform where you have released your unofficial build
```
https://t.me/garbageofreache/41?single (v 4.3)
https://github.com/Thereache/releases/releases/tag/V4.4-awaken (v4.4)
```

## Other ROM's you maintain officially or unofficially
```
1 Rom(ProjectBlaze Official)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
5 Months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
Thereache
```

**Comment by arnavpuranik** [comment]
I cannot find your trees, they seem to be private. Closed since this is a violation of rule 4 from our Maintainer COC.
