### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Muichiro09** [Project-Awaken/official_devices#120]
## Device you want to apply for
``` 
Poco X3/NFC
``` 
## Device tree sources

https://github.com/Muichiro-s-Lab/device_surya/tree/Project-Awaken
https://github.com/surya-aosp/arise_xiaomi_surya
https://github.com/Muichiro-s-Lab/vendor_surya/tree/lineage-21

## Link to the platform where you have released your unofficial build
https://t.me/POCOHUB_X3EN/3881
```

## Other ROM's you maintain officially or unofficially
```
Superior Extended - Official 
Project Matrixx - Unofficial 
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1 year +
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

## Contact
### Telegram username
```
@muichir09
```

**Comment by Muichiro09** [comment]
https://t.me/suryabuilds/334

Apologies for the wrong link for unofficial build here's the correct one.

Have a Good Day! Thanks.

**Comment by KrishnakantShedge** [comment]
You are maintaining more than 3 ROMS (AwakenOS, SuperiosExtended, Matrixx, PixelOS) which is against the Maintainer requirements.

**Comment by Muichiro09** [comment]
Hi Sir 

Hope all is well im not maintaining PixelOS sir i build it to test the QPR2 trees that time.

If you have any questions let me know 
Thanks.

**Comment by KrishnakantShedge** [comment]
What about Infinity?

**Comment by Muichiro09** [comment]
Hi Sir 

Infinity is the rebrand for Superior Extended
