### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by SKetU-l** [Project-Awaken/official_devices#122]
## Device you want to apply for
```
Asus Zenfone Max Pro M1 (X00T/D)
```

## Device tree sources

```
https://github.com/SKetU-l/device_asus_X00TD-4.19
https://github.com/SKetU-l/device_asus_sdm660-common-4.19
https://github.com/SKetU-l/vendor_asus-4.19
https://github.com/SKetU-l/kernel_asus_sdm660-4.19
```

## Link to the platform where you have released your unofficial build
```
https://t.me/bruhell/282 (v3.10) 
```

## Other ROM's you maintain officially or unofficially
```
RisingOS
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1-2 years
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@SKetUl
```

**Comment by arnavpuranik** [comment]
Hey, So this is what I think personally:

1. There's No Awaken Branch on your [device tree](https://github.com/SKetU-l/device_asus_X00TD-4.19)? 
2. You have added an Awaken 3.x build as your unofficial build which is unsupported. We do not maintain legacy versions of AwakenOS. 
3. I saw you're maintaining Multiple ROMs on your channel, but you haven't mentioned them in your form, I saw LineageOS, Rising (which you've mentioned) but other builds too like Bootleggers, RiceDroid, SuperiorOS etc. We allow maximum number of ROMs as 3 including AwakenOS according to our [Maintainer COC](https://github.com/Project-Awaken/official_devices/blob/ursa/maintainerreq.md).

Hence, you're rejected.

**Comment by SKetU-l** [comment]
Thanks for the revew

1. I moved to different trees.
2. I was inactive, so when I came back to the community recently, I swear my device boots AwakenOS.
3. Other ROMs are not being maintained regularly, not really buildbotting but kind of. I maintain Rising officially and Awaken unofficially (I will continue to do so too).

Thanks, I appreciate your suggestions.

**Comment by arnavpuranik** [comment]
> Thanks for the revew
> 1. I moved to different trees.

In any case, your review happens with the trees you've applied with. 

> 2. I was inactive, so when I came back to the community recently, I swear my device boots AwakenOS.

We can't take you on the basis of "trust me bro". 

> 3. Other ROMs are not being maintained regularly, not really buildbotting but kind of. I maintain Rising officially and Awaken unofficially (I will continue to do so too).
 
You should've mentioned it in that case. 

> Thanks, I appreciate your suggestions.
