### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by kibria5** [Project-Awaken/official_devices#123]
## Device you want to apply for
```
Redmi Note 7 Pro (violet)
```

## Device tree sources
```
https://github.com/kibria5/device_xiaomi_violet.git
https://github.com/kibria5/vendor_xiaomi_violet.git
https://github.com/kibria5/kernel_xiaomi_violet.git
```

## Link to the platform where you have released your unofficial build
```
https://t.me/RedmiNote7ProChannel/2774
```

## Other ROM's you maintain officially or unofficially
```
Evolution X
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2.5 years
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@kibria5
```

**Comment by arnavpuranik** [comment]
I saw you are building multiple ROMs like CrDroid, Bananadroid, Zephyrus etc. which you haven't mentioned in your form. We allow maximum number of ROMs as 3 including AwakenOS according to our [Maintainer COC](https://github.com/Project-Awaken/official_devices/blob/ursa/maintainerreq.md).

Hence, you're rejected.

**Comment by kibria5** [comment]
> I saw you are building multiple ROMs like CrDroid, Bananadroid, Zephyrus etc. which you haven't mentioned in your form. We allow maximum number of ROMs as 3 including AwakenOS according to our [Maintainer COC](https://github.com/Project-Awaken/official_devices/blob/ursa/maintainerreq.md).
> 
> Hence, you're rejected.

i dropped all that roms
