### ISSUE TITLE
New maintainer for Lavender

### ISSUE THREAD

**Issue by Vitorgl2003** [Project-Awaken/official_devices#13]
## Device you want to apply for
```
Xiaomi Redmi Note 7 - Lavender
```

## Device tree sources
```
https://github.com/Vitorgl2003/device_xiaomi_lavender/tree/awaken
https://github.com/Vitorgl2003/vendor_xiaomi_lavender/tree/awaken
https://github.com/Vitorgl2003/kernel_xiaomi_lavender
```

## Link to the platform where you have released your unofficial build
```
https://www.pling.com/p/1657599/
```

## Other ROM's you maintain officially or unofficially
```
Spark - Officialy, Awaken, AEX- UnOfficialy
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 months and 3 weeks
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@bitortheaddicted
```

**Comment by raghavt20** [comment]
We are not sparkOS, the trees you linked don't have any Bringup regarding Project Awaken

**Comment by Vitorgl2003** [comment]
> We are not sparkOS, the trees you linked don't have any Bringup regarding Project Awaken

Good Night sir, sorry for inconvenience, links are updated with stuffs fixed, check it again please.

**Comment by KrishnakantShedge** [comment]
Can you clarify the situation where the Pling shows more builds of other ROMS than you have mentioned here?

**Comment by Vitorgl2003** [comment]
> Can you clarify the situation where the Pling shows more builds of other ROMS than you have mentioned here?
Yes, Im sharing the pling page with other dev, AEX is droped since it have official dev now,  Project Radiant uno will replaced it.
