### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ramaadni** [Project-Awaken/official_devices#132]
## Device you want to apply for
```
POCO X6 5G/Redmi Note 13 Pro 5G (garnet)
```

## Device tree sources

```
https://github.com/garnet-stuff/device_xiaomi_garnet/tree/ursa
https://github.com/garnet-stuff/device_xiaomi_garnet-kernel
https://github.com/garnet-stuff/vendor_xiaomi_garnet
https://git.mainlining.org/ramaadni/proprietary_vendor_xiaomi_garnet-miuicamera
```

## Link to the platform where you have released your unofficial build
```
https://t.me/rmdnscape/64
```

## Other ROM's you maintain officially or unofficially
```
ProjectEverest (Unoffical)
AlphaDroid (just a test build and not continuing)
```

## Bugs on unofficial build
```
Fingerprint sensor turns on everywhere (But it only happens on some devices)
```

## How long have you been building for?
```
1 Month
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes. because not have proper kernel source, kernel source is broken.
```

### Telegram username
```
@ramaadni
```

**Comment by KrishnakantShedge** [comment]
We are closing the maintainers' form for now. Please re-apply for A15.
