### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by JonnyRoller23** [Project-Awaken/official_devices#17]
## Device you want to apply for
```
Redmi 8A (olivelite)
```

## Device tree sources

```
https://github.com/olivelite-trees/device_xiaomi_olivelite
https://github.com/olivelite-trees/vendor_xiaomi_olivelite
https://github.com/olivelite-trees/device_xiaomi_olivelite-common
https://github.com/olivelite-trees/vendor_xiaomi_olivelite-common
https://github.com/JonnyRoller23/kernel_xiaomi_olivelite_12
```

## Link to the platform where you have released your unofficial build
```
https://drive.google.com/uc?id=1MF1hbRJcJx-hTuhUc0CT12N3T9eOIQ6y&export=download
```

## Other ROM's you maintain officially or unofficially
```
I don't officially support anything, but unofficially (crDroid 12, AwakenOS 12, ProjectRadiant 12)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Years
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No
```

### Telegram username
```
@JonnyRoller23
```

**Comment by BladeRunner-A2C** [comment]
Your device sources does not have any proper authorship & commit history which doesn't pass our guidelines henceforth we won't be allowing your application.
Have a nice day..
