### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by NotZeetaa** [Project-Awaken/official_devices#21]
## Device you want to apply for
```
Poco F2 Pro (Lmi)
```

## Device tree sources

```
https://github.com/NotZeetaa/device_xiaomi_lmi-2
https://github.com/NotZeetaa/device_xiaomi_sm8250-common-3
https://github.com/projects-nexus/android_kernel_xiaomi_sm8250
https://github.com/RealSchnedi/vendor_xiaomi_lmi
https://github.com/RealSchnedi/vendor_xiaomi_sm8250-common
```

## Link to the platform where you have released your unofficial build
```
https://drive.google.com/file/d/1GR-Fc_TdCCU9uAdIJUeNwi5_Y4E9ks0D/view?usp=drivesdk
```

## Other ROM's you maintain officially or unofficially
```
Pixel Extended, Project Radiant, Aicp unofficially 
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
4/5 months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@NotZeetaa
```

**Comment by KrishnakantShedge** [comment]
Rejected. Why?
1. You are already maintaining 3 ROM apart from Awaken.
 
2. Improper commits:
https://github.com/NotZeetaa/device_xiaomi_lmi-2/commit/234003fd34cca2901045bdbd80c6b5edbd96f6f9
https://github.com/NotZeetaa/device_xiaomi_lmi-2/commit/bb23fa4f1b90ef7dd99937251c2ff33a1dc73c53

You changed CPU variants and again changed back and again changed:
https://github.com/NotZeetaa/device_xiaomi_sm8250-common-3/commit/12c6a98663c6b3be9a7b56191c030b969fd0ba03
https://github.com/NotZeetaa/device_xiaomi_sm8250-common-3/commit/263c29b04ebe57fbd216dda097c550b3a66100ec
https://github.com/NotZeetaa/device_xiaomi_sm8250-common-3/commit/4a0ce9eb89a51e717554932f9f4c4da8fd6fa554

Also, why are there so many reverts in the common device trees? Some seem not even needed:
https://github.com/NotZeetaa/device_xiaomi_sm8250-common-3/commit/e12d647bc7f627c18733b700237c66ac4200a017
https://github.com/NotZeetaa/device_xiaomi_sm8250-common-3/commit/a1340d6909d7a992ca13d6f9bcb6c13f14699e75

Talking about your kernel:
https://github.com/projects-nexus/android_kernel_xiaomi_sm8250/commit/44f8cdb45017505415dcc8be503d625222487ac3
https://github.com/projects-nexus/android_kernel_xiaomi_sm8250/commit/5e2cb112282cc9fc35d624cd47e2e7216c0986bd
https://github.com/projects-nexus/android_kernel_xiaomi_sm8250/commit/6f7b3f39df8beba8e2652bb70bddf4503cf387d8
https://github.com/projects-nexus/android_kernel_xiaomi_sm8250/commit/7a944a65ec66fa1f9dd607b7498df994d4523101
Ever thought about writing what are you changing in the commit message?

See the commit message here:
https://github.com/projects-nexus/android_kernel_xiaomi_sm8250/commit/b341293efc353f87debf3bdf7ec2a9e42d7b05c9

Test commits:
https://github.com/projects-nexus/android_kernel_xiaomi_sm8250/commit/01e9cd5f57e5579b6829e6cb76761950ab1cf89e
https://github.com/projects-nexus/android_kernel_xiaomi_sm8250/commit/4a0e4bc55486dd135e695f363798664708a32a8e
https://github.com/projects-nexus/android_kernel_xiaomi_sm8250/commit/aaadd8505853705f5b7c3c354ea223cd1c2fdbdd

3. Seeing your trees, I can understand you don't know about resetting and rebasing in git.

4. Why was a Gdrive link provided? We expect you to share the post where you have published your build

**Comment by NotZeetaa** [comment]
About rebasing the revert commits, i did it already(I didn't before because i had lazy lul)
About the "ci: Updates" commits its my build.sh to build my kernel i don't think i need to specific say what was changed or i need?
About the test commits it was tested months ago but i forgot to amend that
I did the following commits to cpu variant to doesn't mess and people blame me because of author of the commits

**Comment by KrishnakantShedge** [comment]
Glad you answered and resolved clarified the situation. But still haven't addressed most of the major ones, mostly DT related side and reverted commits because I can still see those commits in your trees. 
About the CI commits, it is needed to write what you have done, not just "Updates".
At least keep one commit for CPU variant changes, You have the change, then revert and then change again.
And there has been a change where only 3 ROM can be maintained (including Awaken) if you want to apply for Official.

**Comment by NotZeetaa** [comment]
> Glad you answered and resolved clarified the situation. But still haven't addressed most of the major ones, mostly DT related side and reverted commits because I can still see those commits in your trees. About the CI commits, it is needed to write what you have done, not just "Updates". At least keep one commit for CPU variant changes, You have the change, then revert and then change again. And there has been a change where only 3 ROM can be maintained (including Awaken) if you want to apply for Official.

About the reverted commits i rebased already in another tree  because of the fork i need to create another repo
About the 3 roms i "support" idk if u understand the previous message i don't support anymore that roms i just built for testing nothing more
And Yhea from here i will spcify the ci commits
Can i open another issue to apply for official?

**Comment by KrishnakantShedge** [comment]
Clean the trees and make sure about how many ROMS you'll be building. You can try again

**Comment by NotZeetaa** [comment]
> Clean the trees and make sure about how many ROMS you'll be building. You can try again

For Now Just Awaken i have a limited storage xD
