### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by iaiaian1** [Project-Awaken/official_devices#22]
## Device you want to apply for
```
Redmi 7a (pine)
```

## Device tree sources

```
https://github.com/iaiaian1/device_xiaomi_pine
https://github.com/iaiaian1/device_xiaomi_sdm439-common
https://github.com/iaiaian1/android_kernel_xiaomi_sdm439
https://github.com/iaiaian1/vendor_xiaomi_pine
https://github.com/iaiaian1/vendor_xiaomi_sdm439-common
```

## Link to the platform where you have released your unofficial build
```
https://sourceforge.net/projects/iaiaian1-rom-release/files/Redmi7A/AwakenOS/
```

## Other ROM's you maintain officially or unofficially
```
I don't maintain any ROMs officially. Unofficially it would be; AwakenOS 12.0, POSP 12.0, BlissROM 12.0, ArrowOS 12.0.
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@iaiaian1
```

**Comment by BladeRunner-A2C** [comment]
You stated to maintain 4 ROM and your trees says 6,
According to our guidelines you shouldn't be maintaining more than 3 ROMs including Awaken.

Keeping that in mind we won't be accepting your application.
Thanks

**Comment by iaiaian1** [comment]
I dont maintain those actively. I just built those out of curiosity. I will DELETE those if needed.
