### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by NotZeetaa** [Project-Awaken/official_devices#24]
## Device you want to apply for
```
Poco F2 Pro (Lmi)
```

## Device tree sources

```
https://github.com/NotZeetaa/device_xiaomi_sm8250-common-4
https://github.com/NotZeetaa/device_xiaomi_lmi-4
https://github.com/RealSchnedi/vendor_xiaomi_lmi
https://github.com/RealSchnedi/vendor_xiaomi_sm8250-common
https://github.com/projects-nexus/android_kernel_xiaomi_sm8250
```

## Link to the platform where you have released your unofficial build
```
https://t.me/NexusKernelSm8250/14353
```

## Other ROM's you maintain officially or unofficially
```
None
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@NotZeetaa
```

**Comment by KrishnakantShedge** [comment]
Decide which device do you even have:
![image](https://user-images.githubusercontent.com/60281508/160576530-96faabbb-8f93-435e-87f4-89c0883708c9.png)

Just author jhenrique09 rather and credits:
https://github.com/NotZeetaa/device_xiaomi_lmi-4/commit/7bfbb888c0ff546fa8861c1c0f19d949bbdb1d6a

Not even required for Gapps builds
https://github.com/NotZeetaa/device_xiaomi_sm8250-common-4/commit/5184b14df7b3aad12a3cc99b85f9b5045a4c36a1

Also, I have seen you have a lot of derps in your kernel. Start rebasing
