### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by skylark17** [Project-Awaken/official_devices#26]
## Device you want to apply for
Mi 11 Lite
Your device name and codename
Courbet

## Device tree sources

```
https://github.com/skylark17/xiaomi_courbet/tree/awaken
https://github.com/skylark17/kernel_xiaomi_sm6150/tree/hayabusa
https://github.com/youngherna/aosp_vendor_xiaomi_courbet
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
ArcanaOS
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Weeks
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
Ryzen Aura
Your Telegram username
ryzenforce

**Comment by KrishnakantShedge** [comment]
Rejected. Why?

1. Kanged commits:
https://github.com/skylark17/xiaomi_courbet/commit/b6d8447121e49cf1d7a9bc6fc8c19120db8183e1
https://github.com/skylark17/xiaomi_courbet/commit/ed7058b8e1ca9476d34f44ad88764906082b9243
https://github.com/skylark17/xiaomi_courbet/commit/f2f97a118562b94ab861b240e9e02f8326446c77
https://github.com/skylark17/xiaomi_courbet/commit/caa364a9397a5962698c36d9e1afab02cafa044a
https://github.com/skylark17/xiaomi_courbet/commit/543281725adca1954788858a235de35b23b1a28f
https://github.com/skylark17/xiaomi_courbet/commit/df59e51b6c8615f5d40c997189a4b2a1cbbf3fc1
https://github.com/skylark17/xiaomi_courbet/commit/5c627717ff47c57b8b372f7a2305d936875c4a0a

2. Not even related to GCam Go:
https://github.com/skylark17/xiaomi_courbet/commit/9e1cb6cf5307aaba74cba78237df6aafc278c744#diff-247ee86229a709a6e2eedfc1d3c4a557825aee073e20b0112ab76f4ca8e4bc4eR130

3. Dumb commits:
https://github.com/skylark17/kernel_xiaomi_sm6150/commit/2b5cf2d75832f294095a85bee326e09b5f9df0f2
https://github.com/skylark17/kernel_xiaomi_sm6150/commit/ab4ad88e02e032e19417c4e7f7120f15b71cd415
https://github.com/skylark17/kernel_xiaomi_sm6150/commit/bf59ff4310cb79af224a2294f8947734dc998446
