### ISSUE TITLE
New maintainer for Redmi 7/Y3 (onclite/onc)

### ISSUE THREAD

**Issue by officialtechrom** [Project-Awaken/official_devices#27]
## Device you want to apply for
```
Redmi 7/Y3 (onclite/onc)
```

## Device tree sources

```
https://github.com/officialtechrom/device_xiaomi_onclite
https://github.com/officialtechrom/android_kernel_xiaomi_onclite
https://github.com/officialtechrom/vendor_xiaomi_onclite
```

## Link to the platform where you have released your unofficial build
```
https://t.me/oncliteupdates/402
```

## Other ROM's you maintain officially or unofficially
```
Only maintained AWAKEN OS (Unofficially) monthly builds from November 2021 and still maintaining along with CORVUS OS Android 10 was my last build for CORVUS OS (UNOFFICIAL) and now dropped it. 
```

## Bugs on unofficial build
```
Only ViLTE or Carrier video calling rest other things work
```

## How long have you been building for?
```
4 months maintained AWAKEN OS and I am building from August 2021 (Total 7 Months). 
You may not see my enough contributions on Github but I have the proper knowledge of Git and trees handling.  The second reason for not enough contributions is that I am a Youtuber who also makes ROM reviews for this device only and covers some other devices also that's why my contributions are less but from now onwards I will be heavily active and increase my contributions also. Thank you
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@tech_rom
```

**Comment by BladeRunner-A2C** [comment]
Lots of bloat in your your trees

Examples:
- https://github.com/officialtechrom/device_xiaomi_onclite/commit/ecd2cf1303feeebabb265a24173489ac49b0849a
- https://github.com/officialtechrom/device_xiaomi_onclite/commit/99d46fa2548de334a5bce5cba0b342de4a85777c
- https://github.com/officialtechrom/device_xiaomi_onclite/commit/99d46fa2548de334a5bce5cba0b342de4a85777c

And these are irrelevant:
- https://github.com/officialtechrom/device_xiaomi_onclite/commit/96a6108b1c59954f661ad959f5f6d75d1fc76531
- https://github.com/officialtechrom/device_xiaomi_onclite/commit/b055e7f6f0e009e0185c56251e82ba0d02dc8808

**Comment by officialtechrom** [comment]
Hello Sir, 
Thank you for the response and I would like to mention that the conflicts which you have mentioned above have been rectified by rebasing my trees. Thank you and hoping for the positive reply
