### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by redlinegame** [Project-Awaken/official_devices#28]
## OnePlus 7 Pro
```
OnePlus 7 Pro(guacamole)
```

## Device tree sources

```
https://github.com/redlinegame/device_oneplus_guacamole
https://github.com/redlinegame/kernel_oneplus_guacamole
https://github.com/redlinegame/vendor_oneplus_guacamole
```

## Link to the platform where you have released your unofficial build
```
this is the first time
```

## Other ROM's you maintain officially or unofficially
```
no one
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1 day
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
r1klem
```

**Comment by BladeRunner-A2C** [comment]
Hmmm

**Comment by KrishnakantShedge** [comment]
You don't have any idea what you are doing.

**Comment by redlinegame** [comment]
> You don't have any idea what you are doing.

yes, that's why I want to do it.i want to learn it. I have a friend in this, so I can do everything right. I pasted the wrong link because I have several of them, but I've fixed it now. I use translator so meaning may change slightly.

**Comment by BladeRunner-A2C** [comment]
Ok,
https://github.com/redlinegame/Useless_android

**Comment by redlinegame** [comment]
> Ok, https://github.com/redlinegame/Useless_android

Yes, I studied AOSP on the videos on the YouTube channel, but then a friend told me that he could help deal with custom firmware. Why don't you want to let me port your rom to another device? Even if I fail, it won't hurt you.

**Comment by KrishnakantShedge** [comment]
First, go and learn before applying for Official. And you need proper device trees to work with.
