### ISSUE TITLE
New maintainer for Redmi 7a (pine)

### ISSUE THREAD

**Issue by iaiaian1** [Project-Awaken/official_devices#30]
## Device you want to apply for
```
Redmi 7a (pine)
```

## Device tree sources

```
https://github.com/iaiaian1/device_xiaomi_pine
https://github.com/iaiaian1/device_xiaomi_sdm439-common
https://github.com/iaiaian1/android_kernel_xiaomi_sdm439
https://github.com/iaiaian1/vendor_xiaomi_pine
https://github.com/iaiaian1/vendor_xiaomi_sdm439-common
```

## Link to the platform where you have released your unofficial build
```
https://sourceforge.net/projects/iaiaian1-rom-release/files/Redmi7A/AwakenOS/
```

## Other ROM's you maintain officially or unofficially
```
I do not maintain any official rom at the moment. I maintain POSP 12.0 and BlissROM 15.0 for pine unofficially.
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@iaiaian1
```

**Comment by iaiaian1** [comment]
now development is on mi439 (pine+olives) and has been handed to abish/outlaw.

**Comment by BladeRunner-A2C** [comment]
We don't care who you handed over the development,
We didn't even accepted your application at the first place

**Comment by iaiaian1** [comment]
What a nice gentleman.
