### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by azoller1** [Project-Awaken/official_devices#31]
## Device you want to apply for
```
OnePlus8T, unified build with 9R (this ok?) codename: kebab (or lemonkebab for 8T/9R).
```

## Device tree sources

```
https://github.com/azoller1/kernel_sm8250
https://github.com/azoller1/lemonkebab-a12
https://github.com/azoller1/sm8250-common-a12
https://github.com/azoller1/vendor_sm8250-a12
https://github.com/azoller1/oneplus-fwk (need to add dependency or maybe move back into tree)
```

## Link to the platform where you have released your unofficial build
```
https://forum.xda-developers.com/t/rom-a12-awaken-os-v2-4-8t-9r-02-17.4402437/

```

## Other ROM's you maintain officially or unofficially
```
Sakura ROM (may drop soon idk)

https://forum.xda-developers.com/t/rom-official-11-project-sakura-5-2-8t.4322695/

```

## Bugs on unofficial build
```
None. 
```

## How long have you been building for?
```
A few years, on & off
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements. Stable AF
```

## SELinux status?
```
Enforcing. Yes
```

## Are you using a prebuilt kernel? If yes, why?
```
No. No way.
```

### Telegram username
```
https://t.me/Azollr

```

**Comment by azoller1** [comment]
WIll update this soon, will rebase trees and only build for the 8T (kebab)

**Comment by KrishnakantShedge** [comment]
Do make a new issue after rebasing the trees
