### ISSUE TITLE
New maintainer for Tissot

### ISSUE THREAD

**Issue by answer35** [Project-Awaken/official_devices#32]
## Device you want to apply for
```
Xiaomi Mi A1 (Tissot)
```

## Device tree sources

```
https://github.com/answer35/device_xiaomi_tissot
https://github.com/answer35/device_xiaomi_msm8953-common
https://github.com/answer35/kernel_xiaomi_tissot
https://github.com/answer35/vendor_xiaomi_tissot
```

## Link to the platform where you have released your unofficial build
```
https://sourceforge.net/projects/answer35-builds/files/tissot/
```

## Other ROM's you maintain officially or unofficially
```
Previously Official on LegionOS until recently
```

## Bugs on unofficial build
```
Bugs on hardware buttons, fixed on latest update 20220219. Would need PR on fwb and Settings.
```

## How long have you been building for?
```
1 Year approximately
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
answer35
```

**Comment by answer35** [comment]
Is there any way to maintain officially for my device ? Plus, I made changes into fwb and settings so my device get the hardware navigation buttons working with possibility to adjust backlight settings too so I would like to make a PR of this soon if it's ok for you guys.

**Comment by KrishnakantShedge** [comment]
Send the commits you need here. 

We have a different flag for this: 
https://github.com/answer35/los-device_xiaomi_msm8953-common/commit/dc9e8b13ec66f260c79d38ca3d9f4a0a6989ed62

Way too much packages removal:
https://github.com/answer35/los-device_xiaomi_msm8953-common/commits/awaken/remove_packages

Also, why do you have so many concurrent Awaken builds?

**Comment by answer35** [comment]
Oopsie sorry closed it by mistake :)

**Comment by answer35** [comment]
> > > Send the commits you need here.
> > > **I will first need to try/confirm for 2.5 that it is still needed and adaptable**
> > > Please do and link those commits here
**I haven't made it yet on 2.5 since I want to try 2.5 clear to make sure i need to commit it. Will see soon even if I've seen that 2.6 already here so it will probably be on 2.6 build.**
> 
> > > We have a different flag for this: [answer35/los-device_xiaomi_msm8953-common@dc9e8b1](https://github.com/answer35/los-device_xiaomi_msm8953-common/commit/dc9e8b13ec66f260c79d38ca3d9f4a0a6989ed62)
> > > **Can you share flag you are using so I can update in my sources ?**
> > > USE_PIXEL_CHARGER := true
**Okay I made the change for my 2.5 build test.**
> 
> > > Way too much packages removal: https://github.com/answer35/los-device_xiaomi_msm8953-common/commits/awaken/remove_packages
> > > **I need to remove packages so I can be able to build or I have error at the end of building regarding partition size. If you have specific packages that really need to be present, can you please also share it so I can try to build with those included ?**
> > > We don't have a list of specific packages, but the amount of packages you are trying to remove is equivalent of not making a gapps build at all.
**It is still gapps, I have all gapps specific features running well but when I tried to build 2.5 with less packages removed I've got again that error "out of space", also by adding one by one google apps**
> 
> > > Also, why do you have so many concurrent Awaken builds?
> > > **What do you mean ? I made different trials to compare which ROM seems the best overall from my point of view. I was before official on Legion but it was quite dead on their side so I decided to quit. That is when I started to look for a new one to use. eOS is only a trial for a de-Googled Android with a newer android version than last available on official website. But still, I was not satisfied to use it as daily ROM due to safetynet, banking apps, etc...**
> > > Do you upload your test builds as well on your SF?
**Will I was still looking at which ROM I wanted to build yes but since I am focused on awaken, I removed older tests builds because I don't plan to update it.**
