### ISSUE TITLE
New maintainer for mido

### ISSUE THREAD

**Issue by anyinglulu1** [Project-Awaken/official_devices#33]
## Device you want to apply for
```
Redmi note 4 (Mido)
```

## Device tree sources

```
https://github.com/anyinglulu1/android_device_xiaomi_mido
https://github.com/anyinglulu1/android_kernel_xiaomi_mido
https://github.com/anyinglulu1/proprietary_vendor_xiaomi
```

## Link to the platform where you have released your unofficial build
```
https://drive.google.com/uc?id=1kh2xTAu1F0zngpXvYTBw1kFcw-f8RBwr&export=download

https://t.me/mido_universal/13191
```

## Other ROM's you maintain officially or unofficially
```
Xtended 
```

## Bugs on unofficial build
```
Screengesture and otg
```

## How long have you been building for?
```
Months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Anyinglulu1
```

**Comment by BladeRunner-A2C** [comment]
No proper commit histories and lots of unnecessary stuffs in trees
