### ISSUE TITLE
Apply for official maintainership for Realme C2

### ISSUE THREAD

**Issue by mrastrange** [Project-Awaken/official_devices#34]
## Device you want to apply for
```
Realme C2 ( RMX1941 )
```

## Device tree sources

```
https://github.com/mrastrange/android_device_realme_RMX1941
https://github.com/mrastrange/android_vendor_realme_RMX1941
```

## Link to the platform where you have released your unofficial build
```
https://t.me/realmec2update/780
```
## Other ROM's you maintain officially or unofficially
```
Xdroid : https://t.me/realmec2update/772
```

## Bugs on unofficial build
```
Double tap to wake
```

## How long have you been building for?
```
For more than 1 month
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes , We Don't have kernel source for Q . Realme Didn't release.
```

### Telegram username
```
@xlpha
```

**Comment by KrishnakantShedge** [comment]
Why is it that I can't see any commit you have done in trees? It's just that you forked and applied for Official. And yes I have also checked other branches.
