### ISSUE TITLE
 support for oneplus 6/6t :)

### ISSUE THREAD

**Issue by optimus9811** [Project-Awaken/official_devices#35]
## Device you want to apply for
```
Oneplus 6/6t
```

## Device tree sources

```
https://github.com/awaken-os-oneplus6-T/proprietary_vendor_oneplus
https://github.com/LineageOS/android_kernel_oneplus_sdm845
https://github.com/awaken-os-oneplus6-T/oneplus_sdm845-common
https://github.com/awaken-os-oneplus6-T/android_device_oneplus_fajita
```

## Link to the platform where you have released your unofficial build
```
(https://sourceforge.net/projects/awakenos-op6-t/files/)
```

## Other ROM's you maintain officially or unofficially
```
Havoc-os 
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Years
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
(https://t.me/OptimussPriime)

**Comment by BladeRunner-A2C** [comment]
Hi,
You should do proper commit messages,
like this one should be https://github.com/awaken-os-oneplus6-T/device_oneplus_sdm845-common/commit/725d4b0ffeb473acba16c21db685040fa9af4eb5 "sm8150-common: Drop lineage livedisplay"

We don't support packages remove:
https://github.com/awaken-os-oneplus6-T/device_oneplus_sdm845-common/commit/4c830ed0604b42b45cef27a3686e02437431fbd9

And this one seems missing authorship:
https://github.com/awaken-os-oneplus6-T/device_oneplus_sdm845-common/commit/dd6dea8b7a1168c287819fe2b13cbf50b9a01038 (original: https://github.com/Project-Awaken/device_xiaomi_beryllium/commit/b71a17610ad3ac6bfcab331d1cce394509e43aac )

**Comment by optimus9811** [comment]
regarding  remove i have to use it bec i have 2.8 max system partition  & i want to cook only gapps for that i have to nuke some apps without nuking i can't cook rom zip 
-all other fixed

**Comment by KrishnakantShedge** [comment]
You aren't giving proper authorship to the commits you have

No proper authorship:
https://github.com/awaken-os-oneplus6-T/oneplus_sdm845-common/commit/4960e2a899f2be6a776201c064fa505e3038ad52
https://github.com/awaken-os-oneplus6-T/oneplus_sdm845-common/commit/fdf1012f81e0b51d265cc42a09c032375a47f952

What do you mean here by Awaken features:
https://github.com/awaken-os-oneplus6-T/oneplus_sdm845-common/commit/c0b79832a34ef81fc0a51bb9338f08927ef2960a

Just commit this properly:
https://github.com/awaken-os-oneplus6-T/oneplus_sdm845-common/commit/b50145a1d27067874245cfe93776f51f8ab9b194

Why is product property override is written here? You could have at least checked the file in which you are committing
https://github.com/awaken-os-oneplus6-T/oneplus_sdm845-common/commit/b6bfcf756532260dcc179fcbdd13bfbf114c729b

**Comment by optimus9811** [comment]
> Again no author: [awaken-os-oneplus6-T/oneplus_sdm845-common@988f722](https://github.com/awaken-os-oneplus6-T/oneplus_sdm845-common/commit/988f722910b3ddd6d22e961849aa723b4c7bec18)
> 
> Wrong author: [awaken-os-oneplus6-T/oneplus_sdm845-common@5a793a6](https://github.com/awaken-os-oneplus6-T/oneplus_sdm845-common/commit/5a793a66bb6534319884a9e33acc78fdab30c6e7)
> 
> Needs proper authorship: [awaken-os-oneplus6-T/oneplus_sdm845-common@3c159b4](https://github.com/awaken-os-oneplus6-T/oneplus_sdm845-common/commit/3c159b48c6f1cd6a47a153d60c9e27b23f91da73)

 Regarding 1 i can fix 
Regarding 2 that's cherry-pick by someone go and check
Another person I'd already mentioned
Regarding 3 - idk what you want even i seen non added this that's my own commit

But ok.     I'll check if my mood changes
Because totally unnecessary  regarding commit 3

**Comment by optimus9811** [comment]
now fixed [https://github.com/awaken-os-oneplus6-T/oneplus_sdm845-common/commits/12.1](link)
