### ISSUE TITLE
New maintainer Poco X3 NFC (Surya)

### ISSUE THREAD

**Issue by Forenche** [Project-Awaken/official_devices#36]
## Device you want to apply for
``` 
Poco X3 NFC - Surya
```

## Device tree sources

```
https://github.com/Forenche/device_xiaomi_surya
https://github.com/Forenche/kernel_xiaomi_surya-priv
https://github.com/Forenche/device_xiaomi_J20C-sepolicy
https://github.com/Forenche/device_qcom_common
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_surya
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_qcom_common
```

## Link to the platform where you have released your unofficial build
```
https://t.me/SuryaStormbreaker/27
```

## Other ROM's you maintain officially or unofficially
```
Only AwakenOS
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 weeks
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@GigaChadCat
```

**Comment by KrishnakantShedge** [comment]
Accepted
