### ISSUE TITLE
New maintainer for Realme C2 (RMX1941)

### ISSUE THREAD

**Issue by ok-ano0s** [Project-Awaken/official_devices#39]
## Device you want to apply for
```
Realme C2 (RMX1941)
```

## Device tree sources

```
https://github.com/ok-ano0s/android_device_realme_RMX1941
https://github.com/ok-ano0s/android_vendor_realme_RMX1941
```

## Link to the platform where you have released your unofficial build
```
https://t.me/realmec2update/789

```

## Other ROM's you maintain officially or unofficially
```
PalladiumOS (OFFICIAL)
```

## Bugs on unofficial build
```
Dt2w
```

## How long have you been building for?
```
1 year
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes. Because Realme hasn't released Android 10 based kernel source for our device.
```

### Telegram username
```
@ok_ano0s and @xlpha
```

**Comment by KrishnakantShedge** [comment]
Your reputation isn't good considering the issues you had

**Comment by ok-ano0s** [comment]
may i know what issue? cuz ik my reputations is kinda.....
