### ISSUE TITLE
Alioth Official

### ISSUE THREAD

**Issue by drkphnx** [Project-Awaken/official_devices#4]
## Device you want to apply for
```
Device name :- poco F3/Mi 11x
Device Code name :-  Alioth/AliothIN
```

## Device tree sources

```
https://github.com/drkphnx/device_xiaomi_sm8250-common
https://github.com/drkphnx/device_xiaomi_alioth
https://github.com/drkphnx/vendor_xiaomi
https://github.com/GZR-Kernels/Optimus_Drunk_Alioth
```

## Link to the platform where you have released your unofficial build
```
https://t.me/pocoF3GlobalUpdates/906
```

## Other ROM's you maintain officially or unofficially
```
Iron Os 
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@darkphnx
```

**Comment by PainKiller3** [comment]
Cleanup your tree

**Comment by drkphnx** [comment]
can you please Guide me what cleanup is needed

**Comment by KrishnakantShedge** [comment]
Drop: https://github.com/drkphnx/device_xiaomi_alioth/commit/d3e7237e16534198f5488473a6fc44b4991c5771
https://github.com/drkphnx/device_xiaomi_alioth/commit/e93aa7e9f6c74ac052ba5557a3cce6d86b6d72b5

Added more overlays than mentioned: https://github.com/drkphnx/device_xiaomi_alioth/commit/4d489b6ca7842644f2c7381dbd6c6bd6d988cc34

Not needed: https://github.com/drkphnx/device_xiaomi_alioth/commit/9afc03d9ee09d14c90033917bb36adb399d09a01
https://github.com/drkphnx/device_xiaomi_alioth/commit/7b39f8ed638810d3c76e161aa2d88883feb77979

Use proper commit title formats:
https://github.com/drkphnx/device_xiaomi_alioth/commit/fa1107e0d83326180cd7d6a20d650c14a065c685
https://github.com/drkphnx/device_xiaomi_alioth/commit/0f4308bccbb6671796033ea0522e1b9644ec410f

Authorship:
https://github.com/drkphnx/device_xiaomi_alioth/commit/2f0939995420521bea3909cf4418f157afb74e34

Why even build Gapps build?: https://github.com/drkphnx/device_xiaomi_alioth/commit/d829022969e9799a7bec64f89fcbdbd2290afd93

You derped here: https://github.com/drkphnx/device_xiaomi_alioth/commit/6f4a36bcc5c322856ae522ef25dab0c7312f521c

Use these as examples and start cleaning.

**Comment by drkphnx** [comment]
done 
https://github.com/drkphnx/device_xiaomi_alioth/tree/12.1

**Comment by raghavt20** [comment]
> done https://github.com/drkphnx/device_xiaomi_alioth/tree/12.1

i would like to see consistency amoung commit messages too.

**Comment by drkphnx** [comment]
?

**Comment by KrishnakantShedge** [comment]
> ?

https://github.com/drkphnx/device_xiaomi_alioth/commit/3180b96f3da642ac68c5edaafd8d2a3faa7ac08e alioth alioth
https://github.com/drkphnx/device_xiaomi_alioth/commit/d0d954381f82ff06fc782ae17d13daf7f3ad6f54 "Alioth

**Comment by drkphnx** [comment]
![jk](https://user-images.githubusercontent.com/80503611/151945666-a4e13d54-a932-4267-b3e8-1be4dd2917aa.png)
