### ISSUE TITLE
New maintainer For mi439

### ISSUE THREAD

**Issue by Th30utlaw** [Project-Awaken/official_devices#40]
## Device you want to apply for
```
Redmi 8/Redmi 8a/Redmi 8a Dual/Redmi 7a (mi439)
```

## Device tree sources

```
https://github.com/Th30utlaw/device_xiaomi_mi439
https://github.com/Th30utlaw/device_xiaomi_sdm439-common
https://github.com/Th30utlaw/vendor_xiaomi_sdm439-common
https://github.com/Th30utlaw/vendor_xiaomi_mi439
https://github.com/mi-sdm439/android_kernel_xiaomi_sdm439
```

## Link to the platform where you have released your unofficial build
```
https://t.me/mi_sdm439/322
```

## Other ROM's you maintain officially or unofficially
```
Cipher OS (Unofficial)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
10 Months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@TheWrongDude
https://t.me/TheWrongDude
```

**Comment by KrishnakantShedge** [comment]
Doesn't follow proper commit title:
https://github.com/Th30utlaw/device_xiaomi_mi439/commit/6d3d6e99f95885db3e0b21845a776353ca0809b8
https://github.com/Th30utlaw/device_xiaomi_mi439/commit/714069fb059ff6c08f6d99fbc69e85392dfc7423

And don't expect Official by just doing Awaken bringup
