### ISSUE TITLE
New maintainer for poco x2

### ISSUE THREAD

**Issue by Anky-AD** [Project-Awaken/official_devices#41]
## Device you want to apply for
```
Poco X2 Phoenix
```

## Device tree sources

```
https://github.com/Anky-AD/awaken_device_xiaomi_phoenix.git
https://github.com/Anky-AD/awaken_vendor_xiaomi_phoenix.git
https://github.com/Anky-AD/awaken_kernel_xiaomi_phoenix.git
```

## Link to the platform where you have released your unofficial build
```
https://drive.google.com/file/d/1Wb4VHEcdiVDc7YonNsXydhXMhj3xRFJL/view
```

## Other ROM's you maintain officially or unofficially
```
Project-Elixir (Official)
Cherish OS (Official)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1 Years
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
https://t.me/AD_Anky
```

**Comment by KrishnakantShedge** [comment]
You can't expect Official by just Awaken bringup

**Comment by Anky-AD** [comment]
I know that...why I got rejected bro ?
