### ISSUE TITLE
Realme 5 Series Official

### ISSUE THREAD

**Issue by mishrabiswajit** [Project-Awaken/official_devices#43]
## Device you want to apply for
```
Realme 5 Series (RMX1911, RMX2030, RMX1925 ,RMX1927) (unified codename "r5x")
```

## Device tree sources

```
https://github.com/mishrabiswajit/device_realme_r5x
https://github.com/mishrabiswajit/kernel_realme_r5x
https://github.com/mishrabiswajit/vendor_realme_r5x
```

## Link to the platform where you have released your unofficial build
```
https://t.me/rmx_1911
```

## Other ROM's you maintain officially or unofficially
```
SPARK OS 
```

## Bugs on unofficial build
```
offline charging
```

## How long have you been building for?
```
6 Months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@yourdeathiswaitingforyou
```

**Comment by BladeRunner-A2C** [comment]
Declined due to faking official release
https://t.me/rmx_1911/1476

**Comment by mishrabiswajit** [comment]
Nice 👌👌
