### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by insanejr** [Project-Awaken/official_devices#45]
## Device you want to apply for
```
Motorola Moto G9 plus (Odessa)
```

## Device tree sources

```
https://github.com/insanejr/device_motorola_odessa
https://github.com/insanejr/kernel-motorola-sm6150
https://github.com/insanejr/vendor_motorola
```

## Link to the platform where you have released your unofficial build
```
https://sourceforge.net/projects/customsodessa/files/awakens/Awaken-2.7-Glacier-odessa-UNOFFICIAL-Vanilla-0237-20220506.zip/download
```

## Other ROM's you maintain officially or unofficially
```
Arcana Projecto
Blaze Projecto
Arrow Os
```

## Bugs on unofficial build
```
Dont Have Any Bugs
```

## How long have you been building for?
```
02 Weeks
05 Months
01 Years
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing/Permissive
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username and perfil link
@rafaelodessa https://t.me/rafaelodessa

**Comment by KrishnakantShedge** [comment]
1. You maintain too many ROMS in the first place.
2. Where the heck is the authorship in your trees?
3. Says building for more than a year but doesn't know to keep authorship.
4. Mentioned both Enforcing and Permissive for Selinux status
