### ISSUE TITLE
New Maintainer 

### ISSUE THREAD

**Issue by JaswantTeja** [Project-Awaken/official_devices#50]
## Device you want to apply for
```
Realme 5/5i/5s
RMX1911/RMX2030/RMX1925
```

## Device tree sources

```
https://github.com/JaswantTeja/device_realme_r5x
https://github.com/JaswantTeja/kernel_realme_r5x
https://github.com/JaswantTeja/vendor_realme_r5x
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Realme5Dev/555708
```

## Other ROM's you maintain officially or unofficially
```
None
```

## Bugs on unofficial build
```
Offline Charging
```

## Other Information
```
One of the unified device "Realme 5i ~ RMX2030" Needs a Fingerprint Fix Because it has a different hardware
Fix - https://t.me/RealmemeCloud/513
```

## How long have you been building for?
```
69 days
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
Jaswant Teja
```

**Comment by sarthakroy2002** [comment]
@JaswantTeja How is proprietary blobs pinned, updated and kanged from other device? How to patchelf a blob? How to upstream kernel?

**Comment by JaswantTeja** [comment]
> 

I Don't About The Proprietary Blobs.But I Know Upstreaming kernel You Can Simply Merge The Latest Kernel Version from kernel.org to your kernel

**Comment by takumi021** [comment]
![IMG_20220616_185955_071](https://user-images.githubusercontent.com/89215836/174081580-ce69c0fc-a78f-4b6a-9517-995e3a263d41.jpg)

Caught in realme 720p display

**Comment by BladeRunner-A2C** [comment]
Nice 👌
