### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by arnavpuranik** [Project-Awaken/official_devices#51]
## Device you want to apply for
```
OnePlus 9R - Lemonades (Also 8T since tree is unified)
```

## Device tree sources

```
https://github.com/arnavpuranik/device_oneplus_lemonades/tree/awaken
https://github.com/Project-Zephyrus/meteoric_kernel
https://github.com/arnavpuranik/vendor_oneplus_lemonades
```

## Link to the platform where you have released your unofficial build
```
Exception Given by REIGNZ. 
```

## Other ROM's you maintain officially or unofficially
```
None for 9R.
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1 & Half Year
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
arnavpuranik
```

**Comment by sushmit1** [comment]
🫡

**Comment by arnavpuranik** [comment]
> 🫡

Susmeatttt

**Comment by sushmit1** [comment]
> > 🫡
> 
> Susmeatttt

🌝
