### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by SpectreDev-007** [Project-Awaken/official_devices#60]
## Device you want to apply for
```
Sony Xperia 5 II (pdx206)
```

## Device tree sources

```
https://github.com/XperiaBrickers/device_sony_pdx206
https://github.com/XperiaBrickers/kernel_sony_sm8250
https://github.com/XperiaBrickers/vendor_sony_pdx206
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Xperia007/28298
```

## Other ROM's you maintain officially or unofficially
```
Corvus Official
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1/2 Years
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@SpectreDev
```

**Comment by arnavpuranik** [comment]
Hey, so I did have a look at your trees

1. In your form you have mentioned that you only maintain Corvus, then why do you have 12 branches on your tree? That too all of them are different ROMs? You should mention what you're building or currently actively maintain regardless of whether it is official or unofficial. This is a violation of Rule number 8. Delete all other obsolete branches and just keep what you actively maintain regardless of its status (official/unofficial)
2. You shouldn't ship [OnePlus Dolby on Sony Phones.](https://github.com/XperiaBrickers/device_sony_pdx206/commit/61777f81fac1f8e5e7b0b65519d107f10b0c6219)
3. Commit titles and history seem inconsistent, in some places you've used sm8250-common and pdx206 in others. Rebase and fix those. 
4. Your kernel is a rebrand of someone else's kernel with just 10-12 commits on top which is again not acceptable. Either make your own kernel from scratch or ship someone else's kernel but we're against rebranding kernels unless you have several changes on top of their source. 
5. No need to move [msm_irqbalance to dt](https://github.com/XperiaBrickers/vendor_sony_pdx206/commit/79c0e9763b34acefce67b35f213853a396ce0693) unless you change it frequently. Revert this change. 
6. At the end of your vendor, you have many inconsistent titles yet again. [This ](https://github.com/XperiaBrickers/vendor_sony_pdx206/commit/c9734510e278eb9c796c286b3d959b8698434b61), as well as [this](https://github.com/XperiaBrickers/vendor_sony_pdx206/commit/9392f8b004f84133a346cbe786bec5ffa2f1e6c2) for that matter. 
7. [Wtf is this change](https://github.com/XperiaBrickers/vendor_sony_pdx206/commit/06f33c7590de80e307f03693ce3f0ea8db3b2644)? Also shouldn't it be squashed with your Initialize commit?
8. Even [this should be squashed with your vendor initialization](https://github.com/XperiaBrickers/vendor_sony_pdx206/commit/9f748e4cb03895fc7743ebf806cf9a5eb786c394). 

Anyway, considering all these things, you're unfit for maintaining officially, consider re-applying later.

**Comment by arnavpuranik** [comment]
Hey, so I did have a look at your trees

1. In your form you have mentioned that you only maintain Corvus, then why do you have 12 branches on your tree? That too all of them are different ROMs? You should mention what you're building or currently actively maintain regardless of whether it is official or unofficial. This is a violation of Rule number 8. Delete all other obsolete branches and just keep what you actively maintain regardless of its status (official/unofficial)
2. You shouldn't ship [OnePlus Dolby on Sony Phones.](https://github.com/XperiaBrickers/device_sony_pdx206/commit/61777f81fac1f8e5e7b0b65519d107f10b0c6219)
3. Commit titles and history seem inconsistent, in some places you've used sm8250-common and pdx206 in others. Rebase and fix those. 
4. Your kernel is a rebrand of someone else's kernel with just 10-12 commits on top which is again not acceptable. Either make your own kernel from scratch or ship someone else's kernel but we're against rebranding kernels unless you have several changes on top of their source. 
5. No need to move [msm_irqbalance to dt](https://github.com/XperiaBrickers/vendor_sony_pdx206/commit/79c0e9763b34acefce67b35f213853a396ce0693) unless you change it frequently. Revert this change. 
6. At the end of your vendor, you have many inconsistent titles yet again. [This ](https://github.com/XperiaBrickers/vendor_sony_pdx206/commit/c9734510e278eb9c796c286b3d959b8698434b61), as well as [this](https://github.com/XperiaBrickers/vendor_sony_pdx206/commit/9392f8b004f84133a346cbe786bec5ffa2f1e6c2) for that matter. 
7. [Wtf is this change](https://github.com/XperiaBrickers/vendor_sony_pdx206/commit/06f33c7590de80e307f03693ce3f0ea8db3b2644)? Also shouldn't it be squashed with your Initialize commit?
8. Even [this should be squashed with your vendor initialization](https://github.com/XperiaBrickers/vendor_sony_pdx206/commit/9f748e4cb03895fc7743ebf806cf9a5eb786c394). 

Anyway, I've marked this as an Ongoing review for the time being. I'll keep this as an ongoing review for the next 24 hours, if you reply/fix your tree, I'll reconsider taking you in.

**Comment by SpectreDev-007** [comment]
All of it is now fixed, as for the kernel it has come from an xperia 1 ii (pdx203) which is a very similar device, i have just added improvements for battery life, as time goes on more commits would be added.

**Comment by arnavpuranik** [comment]
Well you deleted your Awaken Branch 🤷🏻

**Comment by SpectreDev-007** [comment]
> Well you deleted your Awaken Branch 🤷🏻

ah yes its out of date since the rebase, i will make a new one

**Comment by SpectreDev-007** [comment]
> Well you deleted your Awaken Branch 🤷🏻

Ok awaken branch is added and kernel has a few changes done to it

**Comment by SpectreDev-007** [comment]
I no longer want to continue
