### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Ghosuto** [Project-Awaken/official_devices#62]
## Device you want to apply for
```
Device :-  POCO F3 / Mi 11X
Device Code name :- Alioth / Aliothin
```

## Device tree sources

```
https://github.com/Ghosuto/device_xiaomi_alioth
https://github.com/Ghosuto/device_xiaomi_sm8250-common
https://github.com/Ghosuto/android_vendor_xiaomi_alioth.git
https://github.com/Ghosuto/android_vendor_xiaomi_sm8250-common
https://github.com/EmanuelCN/kernel_xiaomi_sm8250/tree/staging
```

## Link to the platform where you have released your unofficial build
```
https://t.me/pocoF3GlobalUpdates/1646
```

## Other ROM's you maintain officially or unofficially
```
None
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
5 Months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Ghosuto7
```

**Comment by arnavpuranik** [comment]
1. [Why did you change your copyright headers](https://github.com/Ghosuto/device_xiaomi_alioth/commit/d51fccfab506f21a3ce8501e2821fd628fcb16f7)? 
2. Fix [this](https://github.com/Ghosuto/android_vendor_xiaomi_sm8250-common/commit/b8fac5c5ccf1b32c098904c19e952e8fcc34ff1c) title and make it consistent with the rest of your vendor

Rest of it seems to be fine from my side.

**Comment by Ghosuto** [comment]
Done sir. Fixed both commits .

**Comment by Ghosuto** [comment]
![Uploading IMG_20221230_205749_906.png…]()

**Comment by Ghosuto** [comment]
![IMG_20221230_205749_906](https://user-images.githubusercontent.com/90827302/210086741-4a9e056e-c7ed-4c34-baf6-a188abac05c5.png)

**Comment by Ghosuto** [comment]
🥲🥲
