### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ghost** [Project-Awaken/official_devices#64]
## Device you want to apply for
```
Redmi Note 10 Pro <sweet>
```

## Device tree sources
https://github.com/Sweet-stuff/device_xiaomi_sweet.git
    https://github.com/Sweet-stuff/kernel_xiaomi_sweet.git
   https://github.com/Sweet-stuff/device_xiaomi_sm6150-common
   https://github.com/Sweet-stuff/vendor_xiaomi
```

```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
2 official roms
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1.2 years
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@aarav_x
```

**Comment by KrishnakantShedge** [comment]
Could you fill out your form correctly first? It doesn't mention which ROM you have built before as well as the link to the unofficial awakenOS build.
