### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by riju2007** [Project-Awaken/official_devices#66]
## Device you want to apply for
```
Redmi Note 11
```

## Device tree sources

```
https://github.com/riju2007/device_xiaomi_spes.git
https://github.com/riju2007/kernel_xiaomi_spes_header-1.git
https://github.com/riju2007/vendor_xiaomi_spes-1.git
```

## Link to the platform where you have released your unofficial build
```
https://sourceforge.net/projects/spes13/files/awaken-3.3-triton-spes-unofficial-vanilla-0949-20230106.zip/download
```

## Other ROM's you maintain officially or unofficially
```
Arrow os Unofficial
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
Base trees i have forked...but bugs or errors i solve on my own in the tree, and there is no kernel source yet for spes
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes, there is no Kernel source yet
```

### Telegram username
```
riju2007
```

**Comment by riju2007** [comment]
i have missed one thing.....it's 6 months

**Comment by riju2007** [comment]
codename-spes

**Comment by KrishnakantShedge** [comment]
All I can see is nothing you have done; the only thing you did is just bringup that too done using GitHub web.
