### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by bhaskar966** [Project-Awaken/official_devices#67]
## Device you want to apply for
```
Redmi Note 10 Pro (sweet)
```

## Device tree sources

```
https://github.com/bhaskar966/device_xiaomi_sweet-1
https://github.com/bhaskar966/device_xiaomi_sm6150
https://github.com/bhaskar966/vendor_xiaomi
https://github.com/RooGhz720/Aghisna_Sweet_Kernel
```

## Link to the platform where you have released your unofficial build
```
https://sourceforge.net/projects/bhaskar-builds/
```

## Other ROM's you maintain officially or unofficially
```
Cherish OS, DerpFest OS, Bliss Rom
```

## Bugs on unofficial build
```
- Issues with miui cam (trying to fix untill then nuke it)
- Deep Sleep (Tend to be fixed)
```

## How long have you been building for?
```
2+ months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate only Squashing (which I will learn soon) of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@iammrbhaskar
```

**Comment by KrishnakantShedge** [comment]
First form related issues:
1. You have made too many builds for sweet technically making you a build bot.
2. We don't ship OEM apps on awakenOS so it's just better to drop it. Fix the deep sleep issue as well.

Now coming to your linked trees:
1. You literally have all the bringup commits in the DT. Some commits miss authors and you have 4 commits with the same name: sweet: overlay: Configure aux camera for Aperture
2. You have the commit and the revert back to back in CT. Just reset it or drop it.
3. What? Wrong commit messages or some changes are messed up. IORapd is dead on 13 https://github.com/bhaskar966/device_xiaomi_sm6150/commit/890cda5669feec34ec096302f8629b1e16d1a97a
https://github.com/bhaskar966/device_xiaomi_sm6150/commit/be4acc4a223b2840128fbaf1689f7ac4aeca042a
https://github.com/bhaskar966/device_xiaomi_sm6150/commit/c3c2879817b5653c71a808e27e00a4d5ea6ad27e
https://github.com/bhaskar966/device_xiaomi_sm6150/commit/ae635c7ab31dee86d36e92a8c1de538117969564
4. Start checking commits before committing them yourself and declaring authors.
5. Care to explain what ozo audio is doing in sweet trees?
6. I know it's not your kernel, but the commits history there is messed up as well
