### ISSUE TITLE
New maintainer 

### ISSUE THREAD

**Issue by MODCORNERS** [Project-Awaken/official_devices#69]
## Device you want to apply for
```
[Samsung Galaxy S10] (beyond1lte)
[Samsung Galaxy S10+] (beyond2lte)
[S10 5G] (beyondx)
[Samsung Galaxy S10e] (beyond0lte)
[Samsung Galaxy Note 10] (d1)
[Samsung Galaxy Note 10+] (d2s)
[Samsung Galaxy Note 10+ 5G] (d2x)
```

## Device tree sources

```
https://github.com/orgs/SealsPlayground/repositories?type=all 

All devices and kernel and vendor are on this github 

```

## Link to the platform where you have released your unofficial build
```
https://forum.xda-developers.com/t/rom-13-unofficial-awaken-os-s10-s10-s10-5g-e.4539153/ (s10 - all)

https://forum.xda-developers.com/t/rom-13-unofficial-awaken-os-d1-d2s-d2x.4539131/ (note 10 - all)


```

## Other ROM's you maintain officially or unofficially
```
https://forum.xda-developers.com/t/rom-r-projectsakura-5-x-for-n10-n10-n10-5g.4341771/#post-87930959 (note 10 - all)

https://forum.xda-developers.com/t/rom-r-projectsakura-5-x-for-s10e-s10-s10.4341767/ (s10 - all)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
I have been building for 1 Year but have not released 
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
MODEDGES
```

**Comment by KrishnakantShedge** [comment]
Commonize trees, show your changes and then reapply
