### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by riju2007** [Project-Awaken/official_devices#74]
## Device you want to apply for
```
Redmi Note 11 - spes
```

## Device tree sources

```
https://github.com/riju2007/device_xiaomi_spes
https://github.com/user/kernel_xiaomi_spes_header
https://github.com/user/vendor_xiaomi_spes
```

## Link to the platform where you have released your unofficial build
```
https://sourceforge.net/projects/spes13/files/awaken-3.3-triton-spes-unofficial-vanilla-0949-20230106.zip/download
```

## Other ROM's you maintain officially or unofficially
```
Bananadroid official, xtended official 
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
5 months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly but i am again refixing my dt as there was some complexities which were violating builds of other roms.....but others remains same, i have tested
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes.....kernel source not released yet
```

### Telegram username
```
@riju2007
```

**Comment by KrishnakantShedge** [comment]
1. You said you were maintaining only Bananadroid and Xtended official but failed to mention ArrowOS and Derpfest alongside awakenOS.
2. I can't see any bringup commit for awakenOS.
3. You have filled the device sources form wrongly.
4. Your commits don't even follow a proper naming scheme
