### ISSUE TITLE
New maintainer 

### ISSUE THREAD

**Issue by KUIxd** [Project-Awaken/official_devices#80]
## Device you want to apply for
```
POCO X3/NFC (Surya/Karna)
```

## Device tree sources

```
https://github.com/KUIxd/device_xiaomi_surya
https://github.com/KUIxd/android_kernel_xiaomi_surya
https://github.com/KUIxd/vendor_xiaomi_surya
```

## Link to the platform where you have released your unofficial build
```
https://t.me/POCOHUB_X3EN/2870
```

## Other ROM's you maintain officially or unofficially
```
none 
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
6 Months 
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@KUIxd

**Comment by KrishnakantShedge** [comment]
Don't want a scammer in maintainers
