### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by JayanthKandula** [Project-Awaken/official_devices#81]
## Device you want to apply for
```
Poco F4 / Redmi K40S (munch)
```

## Device tree sources

```
https://github.com/JayanthKandula/android_device_xiaomi_munch/tree/triton
https://github.com/JayanthKandula/android_device_xiaomi_sm8250-common/tree/triton
https://github.com/JayanthKandula/android_kernel_xiaomi_munch
https://github.com/JayanthKandula/proprietary_vendor_xiaomi_sm8250-common
https://gitlab.com/jayanth-coder/vendor_xiaomi_munch
```

## Link to the platform where you have released your unofficial build
```
https://t.me/PocoF4updates/641
```

## Other ROM's you maintain officially or unofficially
```
PE
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
6 Months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@jayanthk
```

**Comment by Vincent4440** [comment]
huh
