### ISSUE TITLE
New maintainer for veux/peux

### ISSUE THREAD

**Issue by ThePrateekBhatia** [Project-Awaken/official_devices#95]
## Device you want to apply for
```
Poco X4 Pro 5G/ Redmi Note 11 Pro / Pro+ 5G/ veux / peux
```

## Device tree sources

```
https://github.com/ThePrateekBhatia/device_xiaomi_veux
https://github.com/ThePrateekBhatia/kernel_xiaomi_sm6375
https://gitlab.com/ThePrateekBhatia/vendor-xiaomi-veux
```

## Link to the platform where you have released your unofficial build
```

```

## Other ROM's you maintain officially or unofficially
```
Project Elixir (Official)
Cherish OS (Official)
HorizonDroid (Official)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Years
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@FreakyPrateek
```

**Comment by ThePrateekBhatia** [comment]
kindly respond, please.

**Comment by arnavpuranik** [comment]
Okay initially, where even is your Awaken Branch? YOU MUST HAVE A SEPERATE BRANCH FOR AWAKEN. It is like the most basic thing. I do not see an Awaken branch [here](https://github.com/ThePrateekBhatia/device_xiaomi_veux)
Hence, I didn't even check your trees. 
2. Why haven't you released an unofficial build even when there's literally a field in the form to include the link to it and it is written in the rules that it is absolutely MANDATORY to release an unofficial build before you apply? Shows how much you've read the rules. 
3. You're already maintaining 3 ROMs and we also have a rule that 3 should be the maximum number of ROMs you should maintain, again, you haven't read the rules. 
4. What is the reason you uploaded the vendor on your [GitLab](https://gitlab.com/ThePrateekBhatia/vendor-xiaomi-veux)?
5. Inspite of you knowing all of the basic things, which I literally mentioned above, you still have the guts to reply to respond to you on your form? We have our life priorities as well and you clearly need to understand that, we do not do this full time.

Considering all of the things above, you're rejected. Consider Re-applying later.
Also, if you consider to re-apply, you must drop one of your existing ROMs according to [Rule Number 8](https://github.com/Project-Awaken/official_devices/blob/ursa/maintainerreq.md).
