### ISSUE TITLE
New maintainer for apollo

### ISSUE THREAD

**Issue by PiotrZPL** [Project-Awaken/official_devices#96]
## Device you want to apply for
```
Xiaomi Mi 10T / Mi 10T Pro / Redmi K30S Ultra (apollo)
```

## Device tree sources

```
https://github.com/PiotrZPL/device_xiaomi_apollo/tree/awaken-14
https://github.com/PiotrZPL/device_xiaomi_sm8250-common/tree/awaken-14
https://github.com/PiotrZPL/vendor_xiaomi_apollo/tree/awaken-14
https://github.com/PiotrZPL/kernel_xiaomi_sm8250/tree/awaken-14
```

## Link to the platform where you have released your unofficial build
```
https://sourceforge.net/projects/piotrzplbuilds/
```

## Other ROM's you maintain officially or unofficially
```
SuperiorOS (unofficial)
DerpFest (unofficial, mostly for experiments)
Havoc-OS (unofficial, but the ROM is mostly dead)
```

## Bugs on unofficial build
```
Play Protect not certified (global issue)
```

## How long have you been building for?
```
6 months
```

## Did you properly read [Device stability requirements](https://github.com/Project-Awaken/official_devices/blob/12/requirements.md) and [Maintainer requirements](https://github.com/Project-Awaken/official_devices/blob/12/maintainerreq.md) before applying? What part of those requirements do you violate?
```
I read everything properly and I violate none of the requirements.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
https://t.me/PiotrZPL
```

**Comment by arnavpuranik** [comment]
Okay I did have a look at your trees.
1. You have done nothing except the [bring up](https://github.com/PiotrZPL/device_xiaomi_apollo/commits/awaken-14/) on your trees, which I will say is 0 contribution to the trees and is unacceptable whatsoever. You MUST contribute to the trees yourself. 
2. The way you have done the only commit which I see from you is also wrong. There's a format for that which every tree follows and your tree should have a consistent history. The format is. 

> `device: changes you did ` 

3.  You're literally adding your own copyright headers? For what? The files which you haven't even made by yourself and just edited by your own? [This ](https://github.com/PiotrZPL/device_xiaomi_apollo/commit/977bb5998849216c1fb7762472a4a5791d7c0a10) is a clear KANG and is again UNACCEPTABLE. We have a strict NO KANG Policy. 
4. Things happening on your common tree are also questionable, these are things done by the other guy, but still you could've easily fixed these. Like:

[Commit 1 ](https://github.com/PiotrZPL/device_xiaomi_sm8250-common/commit/28761afa3af386b7ac7cc621da2a1f5f7c4f4812)
[Commit 2](https://github.com/PiotrZPL/device_xiaomi_sm8250-common/commit/e4762274387748acf8a174c24dd51de94c958137)

These two commits could've easily been squashed and reformatted and fixed. Shows how good your Git Skills are. 

Considering all of these things, you're rejected. You should consider re-applying later.

**Comment by PiotrZPL** [comment]
@arnavpuranik 
1. Android 14 trees for `apollo` are still under heavy development. Functional A14 builds for this device started appearing just a month ago. I will contribute more, I just need more time.
2. OK, I will apply this format.
3. That's how most open source projects work. Every contributor adds his own copyright notice. If it really bothers you, I will remove them.
4. This commits are marked as [temp], which indicates that they will be changed in the future. As I mentioned in 1., those trees are changing a lot now. Once they stabilise, I will fix every commit.

Nevertheless, I fully understand your decision and will consider re-applying in the future.

**Comment by arnavpuranik** [comment]
> @arnavpuranik
> 
> 1. Android 14 trees for `apollo` are still under heavy development. Functional A14 builds for this device started appearing just a month ago. I will contribute more, I just need more time.

You have to be the one developing, not rely on others for them to develop and pick their commits. Then that is literally buildbotting. Also A14 is new for every device, not just yours so your argument towards your device is not stable is not quite justified.   

> 2. OK, I will apply this format.

Yes, please. 

> 3. That's how most open source projects work. Every contributor adds his own copyright notice. If it really bothers you, I will remove them.

Okay that's not how open-source projects work, this is modifying someone else's work. I'd have still accepted it if you contributed and added several lines of your own to any of these files which someone else has not done or implemented yet, then in that case, I wouldn't have said anything, but clearly you haven't even done that.  
> 4. This commits are marked as [temp], which indicates that they will be changed in the future. As I mentioned in 1., those trees are changing a lot now. Once they stabilise, I will fix every commit.

Even if you mark them as temp, which is fine, still you should keep your commit history clean and push such changes to WIP/staging branches and not on your main branch. Main branch should always have a clean history no matter what.  

> 
> Nevertheless, I fully understand your decision and will consider re-applying in the future.
